# Generated by Django 5.1.2 on 2024-10-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("train_station", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="route",
            name="distance",
            field=models.PositiveIntegerField(),
        ),
    ]
