# Generated by Django 5.1.2 on 2024-10-13 15:37

import train_station.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("train_station", "0003_alter_route_distance"),
    ]

    operations = [
        migrations.AddField(
            model_name="crew",
            name="image",
            field=models.ImageField(
                null=True, upload_to=train_station.models.image_file_path
            ),
        ),
        migrations.AddField(
            model_name="train",
            name="image",
            field=models.ImageField(
                null=True, upload_to=train_station.models.image_file_path
            ),
        ),
    ]
