# Generated by Django 5.1.2 on 2024-10-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("train_station", "0004_crew_image_train_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="station",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="station",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
